services:
  postgres:
    image: postgres:latest
    container_name: 'postgres'
    restart: always
    shm_size: 256M
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_USER:
      POSTGRES_DB:
    volumes:
      - "./sql:/docker-entrypoint-initdb.d/"