version: "2"
run:
  concurrency: 4
  modules-download-mode: readonly
  issues-exit-code: 1
  tests: false
  allow-parallel-runners: false
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - copyloopvar
    - dupl
    - durationcheck
    - errname
    - errorlint
    - gocritic
    - gocyclo
    - gosec
    - misspell
    - nakedret
    - nilerr
    - nilnil
    - noctx
    - prealloc
    - reassign
    - revive
    - staticcheck
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
  settings:
    copyloopvar:
      check-alias: true
    dupl:
      threshold: 300
    gocritic:
      disabled-checks:
        - hugeParam
        - rangeExprCopy
        - rangeValCopy
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gosec:
      excludes:
        - G114
        - G115
        - G301
    misspell:
      locale: US
    revive:
      confidence: 0.8
      severity: warning
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          severity: warning
          disabled: true
        - name: exported
          arguments:
            - checkPrivateReceivers
            - disableStutteringCheck
          severity: warning
          disabled: false
  exclusions:
    generated: lax
    rules:
      - linters:
          - staticcheck
        text: at least one file in a package should have a package comment
      - linters:
          - dupl
          - gosec
        path: _test\.go
    paths:
      - vendor
      - test
      - e2e
      - docker
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: false
  new: false
  fix: false
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/spacemagneto/url-metadata-extractor
  exclusions:
    generated: lax
    paths:
      - vendor
      - test
      - e2e
      - docker
      - third_party$
      - builtin$
      - examples$
